name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim

    steps:
    - uses: actions/checkout@v4

    - name: Install curl
      run: apt-get update && apt-get install -y curl

    - name: Install ExifTool
      run: apt-get install -y libimage-exiftool-perl

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: |
        uv pip install --system -r requirements.txt

    - name: Run tests
      run: |
        python tests/test_metadata_tools.py

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          *.xml 